version: "3.8"

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3001:3001"
    environment:
      - DB_NAME=notification_db
      - DB_USER=postgres
      - DB_PASSWORD=tiger
      - DB_HOST=db  # Use 'db' (container name) instead of 'localhost'
      - JWT_SECRET=your_jwt_secret_key
      - PORT=5000
      - NODE_ENV=production
    depends_on:
      - db
    volumes:
      - .:/app
      - /node_modules

  db:
    image: postgres:15  # Change to mysql:8 if using MySQL
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tiger
      POSTGRES_DB: notification_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
